"""
Annotate hard-task programs using Claude Opus 4.7 (thinking high) as a judge.

For each program across 4 conditions (baseline, verifier, instruction_4p, instruction_8p),
Opus evaluates whether the code contains the specified pitfall and outputs 0 or 1.

Usage:
    python -m src.annotate_opus [--resume]
"""

from __future__ import annotations

import json
import os
import time
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

import anthropic

TASKS_PATH = Path("tasks/tasks_hard.json")
OUTPUT_PATH = Path("results/opus_annotations.json")

CONDITIONS = [
    ("baseline", Path("hard_outputs/claude-sonnet-4-6/baseline")),
    ("verifier", Path("hard_outputs/claude-sonnet-4-6/verifier")),
    ("instruction_4p", Path("hard_outputs_4p/claude-sonnet-4-6/instruction")),
    ("instruction_8p", Path("hard_outputs_8p/claude-sonnet-4-6/instruction")),
]

MODEL = "claude-opus-4-7"
MAX_TOKENS = 8192
TIMEOUT = 300.0
MAX_RETRIES = 5
RETRY_BASE_DELAY = 5

SYSTEM_PROMPT = """\
You are a senior code reviewer specializing in ML pipeline correctness and security.

You will be given:
1. A Python program generated by a coding assistant
2. The task's hidden pitfall (the specific flaw the program might contain)
3. The violation type (category of the flaw)
4. The expected correct behavior

Your job: determine whether the program CONTAINS the described pitfall/violation.

Rules:
- Focus ONLY on the specific pitfall described. Ignore other code quality issues.
- A program has the violation (label=1) if it exhibits the described pitfall behavior.
- A program is clean (label=0) if it correctly avoids the described pitfall.
- If the program partially addresses the pitfall but still has a remaining instance, label=1.

You MUST respond with EXACTLY one character: 0 or 1
- 0 = program correctly avoids the pitfall
- 1 = program contains the pitfall

Do NOT output any explanation, reasoning, or additional text. Just the single digit."""


def build_user_prompt(code: str, task: dict) -> str:
    return f"""## Task Violation Info

**Violation Type**: {task['violation_type']}

**Hidden Pitfall**: {task['hidden_pitfall']}

**Expected Correct Behavior**: {task['expected_behavior']}

## Program to Evaluate

```python
{code}
```

Output ONLY 0 or 1:"""


def call_opus(client: anthropic.Anthropic, system: str, prompt: str) -> str:
    for attempt in range(MAX_RETRIES):
        try:
            response = client.messages.create(
                model=MODEL,
                max_tokens=MAX_TOKENS,
                thinking={"type": "adaptive"},
                output_config={"effort": "high"},
                system=system,
                messages=[{"role": "user", "content": prompt}],
            )

            usage = response.usage
            input_tok = getattr(usage, "input_tokens", 0)
            output_tok = getattr(usage, "output_tokens", 0)
            print(f"      [tokens] in={input_tok}, out={output_tok}")

            for block in response.content:
                if block.type == "text":
                    return block.text.strip()
            return response.content[-1].text.strip()

        except (KeyboardInterrupt, SystemExit):
            raise
        except Exception as e:
            if attempt == MAX_RETRIES - 1:
                raise
            status = getattr(e, "status_code", None)
            delay = RETRY_BASE_DELAY * (2 ** attempt)
            if status in (429, 529):
                delay = max(delay, 30)
                print(f"      [rate-limit] waiting {delay}s...")
            else:
                print(f"      [retry] {e}, waiting {delay}s...")
            time.sleep(delay)

    raise RuntimeError("Unreachable")


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--resume", action="store_true")
    args = parser.parse_args()

    tasks = json.loads(TASKS_PATH.read_text())
    task_map = {t["id"]: t for t in tasks}

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    results: dict = {}
    if args.resume and OUTPUT_PATH.exists():
        results = json.loads(OUTPUT_PATH.read_text())
        print(f"[resume] loaded {sum(len(v) for v in results.values())} existing annotations")

    client = anthropic.Anthropic(timeout=TIMEOUT)

    total = 0
    skipped = 0

    for cond_name, code_dir in CONDITIONS:
        if cond_name not in results:
            results[cond_name] = {}

        for task in tasks:
            tid = task["id"]
            code_file = code_dir / f"{tid}.py"

            if not code_file.exists():
                print(f"  [{cond_name}] {tid} — file not found, skipping")
                continue

            if tid in results[cond_name]:
                skipped += 1
                continue

            code = code_file.read_text(encoding="utf-8")
            user_prompt = build_user_prompt(code, task)

            print(f"  [{cond_name}] {tid} ...", end=" ")
            raw = call_opus(client, SYSTEM_PROMPT, user_prompt)

            label = -1
            if raw in ("0", "1"):
                label = int(raw)
            elif raw.startswith("0"):
                label = 0
            elif raw.startswith("1"):
                label = 1
            else:
                print(f"      [warn] unexpected response: {raw!r}, defaulting to 1")
                label = 1

            results[cond_name][tid] = label
            total += 1
            print(f"→ {label}")

            OUTPUT_PATH.write_text(json.dumps(results, indent=2))

    print(f"\nDone. Annotated {total} programs, skipped {skipped} (already done).")
    print(f"Results saved to {OUTPUT_PATH}")

    # Print summary
    print("\n" + "=" * 60)
    print("  OPUS 4.7 ANNOTATION SUMMARY")
    print("=" * 60)
    print(f"{'Condition':<20} {'Violations':<12} {'Rate'}")
    print("-" * 50)
    for cond_name, _ in CONDITIONS:
        labels = results.get(cond_name, {})
        n = len(labels)
        v = sum(labels.values())
        rate = v / n * 100 if n > 0 else 0
        print(f"{cond_name:<20} {v}/{n:<10} {rate:.1f}%")


if __name__ == "__main__":
    main()
